#!/usr/bin/env bash
set -euo pipefail

# prepare.sh — Normalize Flashcards-Portugues build state for a fresh machine.
# Run this before opening the project in Xcode on a new machine.
# Does NOT build the app — that's for the App Store flow.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

echo "=== Flashcards-Portugues prepare ==="
echo "Root: $ROOT_DIR"
echo

# ---------------------------------------------------------------------------
# 1. Prerequisites
# ---------------------------------------------------------------------------

if ! command -v swift &>/dev/null; then
  echo "❌ swift not found — install Xcode Command Line Tools (xcode-select --install)" >&2
  exit 1
fi

if ! command -v xcodegen &>/dev/null; then
  echo "❌ xcodegen not found — install with: brew install xcodegen" >&2
  exit 1
fi

echo "✓ swift $(swift --version 2>&1 | head -1)"
echo "✓ xcodegen $(xcodegen --version 2>/dev/null || echo 'found')"
echo

# ---------------------------------------------------------------------------
# 2. Resolve the local package path
# ---------------------------------------------------------------------------

# The local package MLXToolbox lives at ../MLXToolbox relative to this repo.
# If it doesn't exist, try to detect nearby repos.
MLX_TOOLBOX="../MLXToolbox"

if [[ ! -d "$MLX_TOOLBOX" || ! -f "$MLX_TOOLBOX/Package.swift" ]]; then
  echo "⚠ MLXToolbox not found at $MLX_TOOLBOX"
  echo "  The local package reference in project.yml won't resolve."
  echo "  Options:"
  echo "    1. Clone MLXToolbox to the sibling directory:"
  echo "       git clone https://github.com/ml-explore/MLXToolbox.git ../MLXToolbox"
  echo "    2. Edit project.yml packages.MLXToolbox.path to point to your copy"
  echo

  # Don't fail here — the user might fix it manually.
  # But we should warn prominently.
else
  echo "✓ MLXToolbox found at $(cd "$MLX_TOOLBOX" && pwd)"
fi
echo

# ---------------------------------------------------------------------------
# 3. Clean stale Xcode state
# ---------------------------------------------------------------------------

echo "--- Cleaning stale Xcode state ---"

# Remove machine-specific user data (Xcode scheme references, breakpoints, etc.)
if [[ -d "FlashcardsPortuges.xcodeproj/xcuserdata" ]]; then
  count=$(find FlashcardsPortuges.xcodeproj/xcuserdata -type f 2>/dev/null | wc -l | tr -d ' ')
  rm -rf FlashcardsPortuges.xcodeproj/xcuserdata
  echo "  Removed $count machine-specific file(s) from xcuserdata/"
fi

# Remove stale workspace (regenerated by xcodegen)
if [[ -d "project.xcworkspace" ]]; then
  rm -rf project.xcworkspace
  echo "  Removed stale project.xcworkspace/"
fi

# Remove stale Package.resolved (will be regenerated from project.yml pins)
if [[ -f "Package.resolved" ]]; then
  rm -f Package.resolved
  echo "  Removed stale Package.resolved"
fi

# Remove derived data references in the project file
if [[ -f "FlashcardsPortuges.xcodeproj/project.pbxproj" ]]; then
  # XCBuildDirectory and XCUserBuildSettings are machine-specific
  sed -i '' 's|XCBuildDirectory.*||g' FlashcardsPortuges.xcodeproj/project.pbxproj 2>/dev/null || true
  echo "  Cleaned derived data paths from project.pbxproj"
fi
echo

# ---------------------------------------------------------------------------
# 4. Regenerate Xcode project from project.yml
# ---------------------------------------------------------------------------

echo "--- Regenerating Xcode project ---"
xcodegen generate
echo "✓ Xcode project regenerated from project.yml"
echo

# ---------------------------------------------------------------------------
# 5. Resolve Swift packages
# ---------------------------------------------------------------------------

echo "--- Resolving Swift packages ---"
swift package resolve
echo "✓ Package.resolved updated"
echo

# ---------------------------------------------------------------------------
# 6. Final state
# ---------------------------------------------------------------------------

echo "=== Done ==="
if [[ -d "$MLX_TOOLBOX" && -f "$MLX_TOOLBOX/Package.swift" ]]; then
  echo "  All dependencies resolved. Open FlashcardsPortuges.xcodeproj in Xcode."
else
  echo "  ⚠ MLXToolbox is missing — fix the package path before building."
fi
